server:
  port: 9001

spring:
  application:
    name: system-gateway-service
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.75.130
    gateway:
      routes:
        # 商品微服务
        - id: goods-service-route
          uri: lb://goods-service
          predicates:
            - Path=/api/goods/**
          filters:
            - StripPrefix= 1
        # 文件上传微服务
        - id: oss-service-route
          uri: lb://oss-service
          predicates:
            - Path=/api/oss/**
          filters:
            - StripPrefix= 1
        # 用户微服务
        - id: user-service-route
          uri: lb://user-service
          predicates:
            - Path=/api/user/**
          filters:
            - StripPrefix= 1
        # 库存微服务
        - id: ware-service-route
          uri: lb://ware-service
          predicates:
            - Path=/api/ware/**
          filters:
            - StripPrefix= 1
        # 后台管理系统（放在最后，低精确Url放于后，高精确Url放于前）
        - id: admin-service-route
          uri: lb://admin-service
          predicates:
            - Path=/api/**
          filters:
            - RewritePath=/api/(?<segment>.*),/tesco-admin/$\{segment}
        # 主机路由（要放在最后）
        - id: tesco-host-route
          uri: lb://goods-service
          predicates:
            # 根据域名进行断言
            - Host=**.tesco.com
  main:
    allow-bean-definition-overriding: true