server:
  port: 8001

spring:
  application:
    name: system-gateway-service
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.75.130
    gateway:
      routes:
        # 商品微服务
        - id: goods-service-consumer
          uri: lb://goods-service
          predicates:
            - Path=/api/goods/**
          filters:
            - StripPrefix= 1
        # 后台管理系统（放在最后，低精确Url放于后，高精确Url放于前）
        - id: admin-service-consumer
          uri: lb://admin-service
          predicates:
            - Path=/api/**
          filters:
            - RewritePath=/api/(?<segment>.*),/tesco-admin/$\{segment}
  main:
    allow-bean-definition-overriding: true