server:
  port: 8002
  servlet:
    session:
      timeout: 30m

spring:
  application:
    name: oauth2-service
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.75.130:8848
    sentinel:
      transport:
        # 数据传输端口
        port: 8719
        # 控制台端口
        dashboard: 192.168.75.158:8858
  session:
    store-type: redis
  redis:
    host: 192.168.75.140
    port: 6379
  # 日期格式设置
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
  thymeleaf:
    cache: false
  main:
    allow-bean-definition-overriding: true

logging:
  level:
    com.jerusalem.goods: debug
