server:
  port: 8084

spring:
  application:
    name: ware-service
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.75.136:3306/tesco-ware?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
    username: root
    password: 123456
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.75.130:8848
    sentinel:
      transport:
        # 数据传输端口
        port: 8719
        # 控制台端口
        dashboard: 192.168.75.158:8858
  rabbitmq:
    host: 192.168.75.156
    port: 5672
    virtual-host: /
    listener:
      simple:
        acknowledge-mode: manual    #手动ack消息
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
  main:
    allow-bean-definition-overriding: true

mybatis-plus:
  mapper-locations: classpath:/mapper/**/*.xml
  global-config:
    db-config:
      id-type: auto
      logic-delete-value: 1
      logic-not-delete-value: 0

logging:
  level:
    com.jerusalem.ware: debug

#设置feign调用超时时间
feign:
  client:
    config:
      default:
        connectTimeout: 60000
        readTimeout: 60000
