server:
  port: 8088

spring:
  application:
    name: seckill-service
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.75.130:8848
    sentinel:
      transport:
        # 数据传输端口
        port: 8719
        # 控制台端口
        dashboard: 192.168.75.158:8858
  redis:
    host: 192.168.75.140
    port: 6379
  session:
    store-type: redis
  rabbitmq:
    host: 192.168.75.156
    port: 5672
    virtual-host: /
  #链路追踪可视化
  zipkin:
    base-url: http://192.168.75.160:9411/
    #关闭服务发现，否则springCloud会把zipkin的url当作服务名称
    discovery-client-enabled: false
    #设置http方式传输数据
    sender:
      type: web
  sleuth:
    sampler:
      probability: 1    # 设置抽样采集率为100%
  thymeleaf:
    cache: false
  mvc:
    date-format: yyyy-MM-dd HH:mm:ss
  main:
    allow-bean-definition-overriding: true
  #设置定时任务线程池
  task:
    execution:
      pool:
        core-size: 5
        max-size: 50
#    scheduling:
#      pool:
#        size: 5

logging:
  level:
    com.jerusalem.order: info