server:
  port: 8088

spring:
  application:
    name: seckill-service
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.75.130:8848
  redis:
    host: 192.168.75.140
    port: 6379
  session:
    store-type: redis
  rabbitmq:
    host: 192.168.75.156
    port: 5672
    virtual-host: /
  thymeleaf:
    cache: false
  mvc:
    date-format: yyyy-MM-dd HH:mm:ss
  main:
    allow-bean-definition-overriding: true
  #设置定时任务线程池
  task:
    execution:
      pool:
        core-size: 5
        max-size: 50
#    scheduling:
#      pool:
#        size: 5
logging:
  level:
    com.jerusalem.order: info