server:
  port: 8001

spring:
  application:
    name: third-service
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.75.130:8848
    alicloud:
      access-key: LTAI4FibE9GHYLSkWS1caFsk
      secret-key: 6fgpnYdXGiGgRrrzMjs4Z3xkXgCWpQ
      oss:
        endpoint: oss-cn-beijing.aliyuncs.com
        bucket: tesco-mall
      sms:
        host: https://feginesms.market.alicloudapi.com
        path: /codeNotice
        appcode: 9f52a37138e64affbcadd1044167a588
        sign: 1
        skin: 5