server:
  port: 8086

spring:
  application:
    name: search-service
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.75.130:8848
  session:
    store-type: redis
  redis:
    host: 192.168.75.140
    port: 6379
  main:
    allow-bean-definition-overriding: true